# [uwsgi]
# wsgi-file = payment.py
# callable = app

# master = true
# processes = 1
# lazy-apps = true
# enable-threads = true

# socket = 0.0.0.0:8080
# protocol = http


[uwsgi]
http = :8080
wsgi-file = payment.py
callable = app
processes = 4
master = true
enable-threads = true
lazy-apps = true
max-requests = 1000
vacuum = true
